# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"randomCharacterPwd": "00_core.ipynb",
         "memorablePwd": "00_core.ipynb",
         "userChoicePwd": "00_core.ipynb",
         "w": "00_core.ipynb",
         "database": "00_core.ipynb",
         "correctPwdType": "00_core.ipynb",
         "usernameFree": "00_core.ipynb",
         "signInCorrect": "00_core.ipynb",
         "signInCount": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fastai.github.io/y9pwd/"

git_url = "https://github.com/fastai/y9pwd/tree/master/"

def custom_doc_links(name): return None
